# Generated by Django 4.2.3 on 2023-07-10 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tickets', to='bug_tracker.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tickets', to='bug_tracker.project'),
        ),
    ]
