# Generated by Django 4.2.3 on 2023-07-13 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tickets',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
