# Generated by Django 4.2.3 on 2023-07-11 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_tracker', '0005_project_tickets_alter_ticket_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_devs',
            field=models.ManyToManyField(blank=True, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
